version: "3"
services:
    flask:
        build: .
        ports:
            - "5000:5000"
        volumes:
            - /.vscode
            - .:/flask-tut
        # env_file:
        #     - env.list

# Run this command: docker-compose run flask bash